In [1]:
from minisom import MiniSom
import pandas as pd
import numpy as np
from collections import defaultdict
import pickle
import matplotlib.pyplot as plt
from numpy import random, linalg, zeros
%matplotlib inline

In [2]:
data_path = '/net/fs04/d2/xgao/SOM'

In [3]:
def get_var(var, prod):
    df = pd.read_csv(data_path+'/'+prod+'/'+prod+'_daily_8019_SCUS_JFMAMOND_'+var+'_anom.txt', header = None, delim_whitespace=True)
    return df

In [4]:
def concat_df(df_list):
    comb_df = pd.concat(df_list, axis = 1)
    comb = comb_df.values
    return comb

In [5]:
ivt_ERA5_df = get_var('ivt','ERA5')

ERA5 = concat_df([ivt_ERA5_df])
data_ERA5 = np.copy(ERA5)
np.random.seed(10)
np.random.shuffle(data_ERA5)

In [7]:
som_shape = (3,4)

In [69]:
def asymptotic_decay(learning_rate, t, max_iter):
    return learning_rate / (1+t/(max_iter/2))

In [70]:
x = som_shape[0]
y = som_shape[1]
input_len = data_ERA5.shape[1]
sigma=.5 
learning_rate=.5,
neighborhood_function='gaussian'
decay_function=asymptotic_decay
topology='rectangular'
random_seed=10

In [18]:
random_generator = random.RandomState(random_seed)

In [28]:
weights = random_generatbor.rand(x,y,input_len)*2-1

In [38]:
weights 

array([[[-0.01240821, -0.21754475, -0.97569451, ...,  0.36458101,
          0.67858748,  0.05261419],
        [-0.87612129, -0.15999964, -0.21220421, ...,  0.59052287,
          0.21989655, -0.58366928],
        [ 0.80579964,  0.13669339, -0.18203949, ..., -0.68853689,
         -0.85043521,  0.57380554],
        [ 0.44614736, -0.22555007, -0.28550998, ..., -0.7540515 ,
         -0.50183637,  0.85676191]],

       [[-0.48938953, -0.32021795, -0.8672862 , ...,  0.42305353,
         -0.40977652,  0.79456638],
        [-0.99719052, -0.05087864,  0.05234299, ...,  0.77472943,
         -0.70009058, -0.62287096],
        [ 0.5759829 ,  0.67485218, -0.98624223, ..., -0.00311683,
          0.91524281,  0.26739541],
        [-0.76781816,  0.0662216 ,  0.95945939, ..., -0.03689144,
         -0.31734545,  0.51232667]],

       [[ 0.00771998, -0.85872257,  0.23379506, ...,  0.71080142,
         -0.13494512,  0.21944954],
        [-0.44935988, -0.56746644,  0.53208634, ..., -0.95957267,
          0.

In [40]:
weights /= linalg.norm(weights, axis = -1, keepdims = True)

In [47]:
activation_map = zeros((x,y))

In [53]:
neigx = np.arange(x)
neigy = np.arange(y)

In [55]:
xx, yy = np.meshgrid(neigx, neigy)

In [59]:
xx,yy

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]))

In [67]:
xx = xx.astype(float)
yy = yy.astype(float)

In [62]:
neigy

array([0, 1, 2, 3])

In [6]:
num_iterations = 5000
data_len = 2009

In [8]:
np.arange(5000)%2009

array([  0,   1,   2, ..., 979, 980, 981])